models:
  - name: daily_sales
    description: "This model calculates the aggregated sales per day."
    columns:
      - name: date
        description: "Date event happened in UTC"
        tests: 
          - not_null
          - unique
      - name: total_sales
        description: "aggregated sales per day"
        tests: 
          - not_null

  - name: daily_states
    description: "This model calculate the daily stats."
    columns:
      - name: date
        description: "Date event happened in UTC"
        tests: 
          - not_null
      - name: visitors
        description: "Number of different users that have visited the store"
        tests: 
          - not_null
      - name: sessions
        description: "Number of different user sessions for the users that have visited the store"
        tests: 
          - not_null
      - name: viewers
        description: "Number of different users that have viewed at least one item"
        tests: 
          - not_null
      - name: views
        description: "Total number of products viewed"
        tests: 
          - not_null
      - name: leaaders
        description: "Number of different users that have added at least one item to the cart"
        tests: 
          - not_null
      - name: leads
        description: "Total number of products added to the cart"
        tests: 
          - not_null          
      - name: purchasers
        description: "Number of different users that have purchased at least one item"
        tests: 
          - not_null
      - name: purchases
        description: "Total number of products purchased"
        tests: 
          - not_null

  - name: daily_funnel
    description: "This model provides ratio of users that make it from one step to the next along the whole journey."
    columns:
      - name: date
        description: "Date event happened in UTC"
        tests: 
          - not_null
      - name: visitors
        description: "Number of different users that have visited the store"
        tests: 
          - not_null
      - name: viewers
        description: "Number of different users that have viewed at least one item"
        tests: 
          - not_null
      - name: leaders
        description: "Total number of products added to the cart"
        tests: 
          - not_null
      - name: purchasers
        description: "Number of different users that have purchased at least one item"
        tests: 
          - not_null
      - name: visitor_to_viewer
        description: "percentage of visitor become viewer"
        tests: 
          - not_null
      - name: viewer_to_leader
        description: "percentage of viewer become leaader"
        tests: 
          - not_null
      - name: leader_to_purchaser
        description: "percentage of leaader become purchaser"
        tests: 
          - not_null

  - name: daily_ticket
    description: "This model provides distribution of the purchase or ticket size is per user daily"
    columns:
      - name: date
        description: "Date event happened in UTC"
        tests: 
          - not_null
          - unique
      - name: total_sales
        description: "aggregated sales per day"
        tests: 
          - not_null
      - name: min_ticket
        description: "min purchase or ticket size per user daily"
        tests: 
          - not_null
      - name: "perc_25th_ticket"	
        description: "25th percentiles purchase or ticket size per user daily"
        tests: 
          - not_null
      - name: "perc_50th_ticket"	
        description: "50th percentiles purchase or ticket size per user daily"
        tests: 
          - not_null
      - name: "perc_75th_ticket"	
        description: "75th percentiles purchase or ticket size per user daily"
        tests: 
          - not_null          
      - name: max_ticket	
        description: "max  purchase or ticket size per user daily"
        tests: 
          - not_null             